/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  20993: {
    YourContract: {
      address: "0xa8af8c57cd369bc9162a6956d70bbba6019e67a7",
      abi: [
        {
          type: "function",
          name: "set",
          inputs: [
            {
              name: "x",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "storedData",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "setEvent",
          inputs: [],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1749823515.json",
      deploymentScript: "Deploy.s.sol",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
